#!/bin/bash

read -r -p 'commit hash: ' hash
read -r -p 'name of tex file to compare: ' filename

gitPath=$(git rev-parse --show-prefix)
#download the file and save it as tmp:
git show $hash:$gitPath$filename > tmp.tex

# get difference file:
latexdiff tmp.tex $filename > tmpdiff.tex

# compile pdf with references:
latexmk -interaction=nonstopmode tmpdiff.tex
latexmk -interaction=nonstopmode tmpdiff.tex
bibtex tmpdiff
latexmk -pdf -interaction=nonstopmode tmpdiff.tex

# clean up so only 1 new file called "Diffed.pdf"
mv -v tmpdiff.pdf Diffed.pdf
rm tmp*